server:
    port: 8084 #系统端口号
    context-path: /ic-iot-ow #应用路径
    #ssl:
     #     key-store: .keystore
     #     key-store-password: 12345678
     #     key-store-type: JKS
    #      key-alias: tomcat

logging:
    level:
        tk.mybatis: TRACE



systemConfig:



